---
- name: Test ARCON API
  hosts: all
  gather_facts: no
  tasks:
    - name: call API
      uri:
        url: http://192.168.56.4:5051/api/GetTargetDevicePassKey
        method: POST
        return_content: true
        headers:
          Authorization: 'bearer fgfdgfgfdgfdg'
      register: output_data
      delegate_to: localhost

    - name: print output
      debug:
        var: output_data.json.Result[3].Password
      delegate_to: localhost

    - name: print output
      debug:
        var: output_data.json.Result[3].UserName
      delegate_to: localhost

    - name: set authentication fact
      set_fact: ansible_user="{{output_data.json.Result[3].UserName}}" ansible_password="{{output_data.json.Result[3].Password}}"

    - name: shell command
      shell: hostname;date
      register: shell_output

    - name: print output
      debug:
        var: shell_output
