---
- name: Test ARCON API
  hosts: localhost
  tasks:
    - name: call API
      uri:
        url: http://192.168.56.4:5051/api/GetTargetDevicePassKey
        method: POST
        return_content: true
        headers:
          Authorization: 'bearer fgfdgfgfdgfdg'
      register: output_data

    - name: print output
      debug:
        var: output_data.json.Result[3].Password

    - name: print output
      debug:
        var: output_data.json.Result[3].UserName

    - name: set authentication fact
      set_fact: ansible_user="{{output_data.json.Result[3].UserName}}" ansible_password="{{output_data.json.Result[3].Password}}"

- name: run command
  hosts: all
  tasks:
    - name: shell command
      shell: hostname;date
