---
- name: Test ARCON API
  hosts: all
  gather_facts: false
  tasks:
    - name: Call API
      ansible.builtin.uri:
        url: http://192.168.56.4:5051/api/GetTargetDevicePassKey
        method: POST
        return_content: true
        headers:
          Authorization: 'bearer fgfdgfgfdgfdg'
      register: output_data
      delegate_to: localhost

    - name: Print output
      ansible.builtin.debug:
        var: output_data.json.Result[3].Password
      delegate_to: localhost

    - name: Print output
      ansible.builtin.debug:
        var: output_data.json.Result[3].UserName
      delegate_to: localhost

    - name: Set authentication fact
      ansible.builtin.set_fact:
        ansible_user: "{{ output_data.json.Result[3].UserName }}"
        ansible_password: "{{ output_data.json.Result[3].Password }}"

    - name: Shell command
      ansible.builtin.command: hostname;date
      changed_when: false
      register: shell_output

    - name: Print output
      ansible.builtin.debug:
        var: shell_output.stdout_lines
