---
- name: deploy code from git to webserver
  hosts: all
  become: true
  tasks:
    - name: clone to localhost
      git:
        repo: 'git@github.com:prasadpatil49/pipeline_test.git'
        dest: /root/pipeline_test
        accept_hostkey: yes
        key_file: /root/.ssh/id_rsa
      delegate_to: localhost
      become_user: root
      ignore_errors: yes

    - name: sync from remote host to destination
      synchronize:
        src: /root/test/pipeline_test/
        dest: /var/www/html/
      delegate_to: localhost
      become_user: root

    - name: restart http service
      service:
        name: httpd
        state: restarted
        enabled: yes
