---
- name: harbor api testing
  hosts: localhost
  gather_facts: no
  tasks:
    - name: hit harbor api
      uri:
        url: https://harbor.dev.mlops.com/api/v2.0/users
        user: "prasad"
        password: "Prasad@123"
        method: POST
        force_basic_auth: yes
        status_code: 201
        headers:
          Content-Type: application/json
        body_format: json
        body:
          comment: "create using api"
          username: "prasadpatil"
          password: "Prasad@123"
          email: "abc@gmail.com"
          realname: "prasad"
        
          
          
      register: apiresult

    - name: print output
      debug: 
        var: apiresult
