---
- name: install and run docker
  hosts: all
  become: true
  tasks:

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - yum:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        enablerepo: docker-ce-nightly
        state: latest

    - service:
        name: docker
        state: started
        enabled: yes

    - pip:
        extra_args: '--trusted-host pypi.org --trusted-host files.pythonhosted.org'
        name:
          - docker
          - docker-compose

    - name: download image
      docker_image:
        name: centos

    - name: build image
      docker_image:
        path: /root
        name: web_image

    - name: launch container
      docker_container:
        name: web
        image: web_image
        state: started
        ports:
          - "8080:80"
        tty: yes
        detach: yes

    - name: Get container info
      docker_host_info:
        containers: yes
      register: result

    - debug:
        var: result.containers

    - shell
        cmd: docker exec -it "{{ item.Id }}" hostname
      with_items: result.containers
