---
- name: install and configure mysql server on centos
  hosts: all
  become: true
  tasks:
    - name: install mysql server
      dnf:
        name: mysql-server
        state: latest


    - name: start mysql-server
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '123456'
        state: present
