---
- name: install and run docker
  hosts: all
  become: true
  tasks:

    - name: Add repository
      yum_repository:
        name: docker
        description: docker repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - yum:
        name: "{{ item }}"
        enablerepo: docker-ce-nightly
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - service:
        name: docker
        state: started
