---
- name: install and check python
  hosts: all
  tasks:

    - name: check
      shell:
        cmd: python3 --version
      register: output

    - name: print
      debug:
        msg: "{{ output.stdout }}"
