---
- name: Install and check python version
  hosts: all
  become: true
  tasks:
    - name: install
      yum:
        name: python3
        state: latest

    - name: check
      shell:
        cmd: python3 --version
      Register: output

    - name: display
      debug:
        msg: "{{ output.stdout }}"
        
