---
- name: linux user creation
  hosts: all
  become: true
  tasks:
    - name: create hash value
      shell:
        cmd: openssl passwd -6 -salt ansible {{ password }}
      register: output

    - name: print hash
      debug:
        msg: "{{ output.stdout }}"