---
- name: Test ARCON API
  hosts: all
  gather_facts: no
  tasks:
    - name: fetch xml data
      uri:
        url: http://www-db.deis.unibo.it/courses/TW/DOCS/w3schools/xml/note.xml
        method: GET
        return_content: yes
      register: output_data
      delegate_to: localhost

    - name: print output
      debug:
        var: output_data