---
- name: Test ARCON API
  hosts: all
  gather_facts: no
  tasks:
    - name: fetch xml data
      uri:
        url: http://www-db.deis.unibo.it/courses/TW/DOCS/w3schools/xml/note.xml
        method: GET
        return_content: yes
      register: output_data
      delegate_to: localhost

    - name: parse xml
      xml:
        xmlstring: "{{ output_data.content }}"
        xpath: /note/to
        content: text

      register: xml_output


    - name: uri output
      debug:
        var: output_data

    - name: xml parse output
      debug:
        var: xml_output