---
- name: install java
  hosts: all
  become: true
  tasks:
    - name: install java
      dnf:
        name: java-11-openjdk-devel
        state: latest
      when: ansible_distribution == "CentOS"
