---
- name: Linux user creation
  hosts: all
  become: true
  tasks:
    - name: Create hash value
      ansible.builtin.command: openssl passwd -6 -salt ansible {{ password }}
      changed_when: false
      register: output

    - name: Print hash
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"

    - name: Creating user
      ansible.builtin.user:
        name: "{{ uname }}"
        comment: user created by ansible
        expires: -1
        password: "{{ output.stdout }}"
